### PR TITLE
fix(kit): date-related mask with month-first mode has incorrect zero-padding logic

### LINKED ISSUE #2141: 🐞 - Date-related mask with month-first mode has incorrect zero-padding logic
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://maskito.dev/kit/date/API?mode=mm%2Fdd%2Fyyyy

### Reproduction
1. Open https://maskito.dev/kit/date/API?mode=mm%2Fdd%2Fyyyy
2. Type `13`

**Expected value:** `01.3|`
**Actual value:** `01.30|`

> Same problem with `yyyy/mm/dd` and `mm/dd` modes!
> It is also an issue for `DateTime` & `DateRange`!

Relates:
* https://github.com/taiga-family/maskito/issues/2005

### Maskito version

3.8.0

### Which browsers have you used?

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by i-timur**
### Summary
Fixed incorrect padding behavior logic and added corresponding tests to ensure proper functionality.
### Reference
Fixes #2141

### CODE REVIEW

File: projects/kit/src/lib/utils/date/validate-date-string.ts [hunk 1]
```diff
@@ -50,8 +50,7 @@ export function validateDateString({
                 return {validatedDateString: '', updatedSelection: [from, to]}; // prevent changes
             }
 
-            validatedDateSegments[segmentName] =
-                `0${segmentValue.slice(0, lastSegmentDigitIndex)}`;
+            validatedDateSegments[segmentName] = `0${segmentValue[0]}`;
```
Comment (nsbarsukov) [inline projects/kit/src/lib/utils/date/validate-date-string.ts]: Let's use `slice(0, -1)`

```suggestion
            validatedDateSegments[segmentName] = `0${segmentValue.slice(0, -1)}`;
```

I hope it provides more self-descriptive code:
```ts
validatedDateSegments[segmentName] = `0${
    segmentValue.slice(0, -1) // <--------------- Without last digit
}`;
dateSegments[i + 1] = [
    nextSegment,
    segmentValue.slice(-1) + // <---------------- Get last digit
        (dateSegments[i + 1]?.[1] ?? '').slice(1),
];
```

P.S. no need to add the such code comments - it is used here only to explain my thoughts
