### PR TITLE
fix(kit): `maskitoStringifyTime` was adding `0` on the wrong side

### LINKED ISSUE #1399: 🐞 - maskitoStringifyTime convert to wrong time
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/79evv4?file=index.ts (see console.log)

### Description

When you convert from "parse time" to "stringify time" some combinations are put wrong, for example:
03:02:00 generates 10920000
But when you try to convert to string it returns:
30:20:00 instead of 03:02:00.

I believe the problem maybe is in the padTimeSegments, which should put "0" at the beginning and not at the end, but messing with this breaks all parse-time.ts tests.

### Maskito version

2.5.0 and 3.0.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by demensky**
Closes #1399

### CODE REVIEW

File: projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts [hunk 1]
```diff
@@ -3,13 +3,13 @@ import type {MaskitoPreprocessor} from '@maskito/core';
...
 import {escapeRegExp} from '../../../utils';
-import {padTimeSegments, validateTimeString} from '../../../utils/time';
+import {padEndTimeSegments, validateTimeString} from '../../../utils/time';
 
 export function createMaxValidationPreprocessor(
     timeSegmentMaxValues: MaskitoTimeSegments<number>,
     timeMode: MaskitoTimeMode,
 ): MaskitoPreprocessor {
-    const paddedMaxValues = padTimeSegments(timeSegmentMaxValues);
+    const paddedMaxValues = padEndTimeSegments(timeSegmentMaxValues);
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts:12]: If I've not mistaken, `padStartTimeSegments` is more suitable here 🤔 

Probably, case with single digit was always broken :D

https://stackblitz.com/edit/time-segment-max-value-bug-single-digit?file=mask.ts

```ts
const timeOptions = maskitoTimeOptionsGenerator({
    mode: 'HH:MM',
    timeSegmentMaxValues: {hours: 4}, // you can enter 09:09 :(
});
```

https://stackblitz.com/edit/time-segment-max-value-bug-single-digit?file=mask.ts

Comment (nsbarsukov) [reply projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts:12]:
```suggestion
    const paddedMaxValues = padStartTimeSegments(timeSegmentMaxValues);
```

\+ add some cypress tests for single-digit cases, please

File: projects/kit/src/lib/masks/date-time/preprocessors/valid-date-time-preprocessor.ts [hunk 2]
```diff
@@ -66,7 +66,7 @@ export function createValidDateTimePreprocessor({
 
         validatedValue += validatedDateString;
 
-        const paddedMaxValues = padTimeSegments(DEFAULT_TIME_SEGMENT_MAX_VALUES);
+        const paddedMaxValues = padEndTimeSegments(DEFAULT_TIME_SEGMENT_MAX_VALUES);
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/date-time/preprocessors/valid-date-time-preprocessor.ts:69]:
```suggestion
        const paddedMaxValues = padStartTimeSegments(DEFAULT_TIME_SEGMENT_MAX_VALUES);
```

**Review by nsbarsukov — CHANGES_REQUESTED** [review]

File: projects/kit/src/lib/masks/date-time/preprocessors/valid-date-time-preprocessor.ts (hunk 2 above)
Comment (demensky) [reply projects/kit/src/lib/masks/date-time/preprocessors/valid-date-time-preprocessor.ts]: This change does not affect anything, but it will be useful for code clarity.

File: projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts (hunk 1 above)
Comment (demensky) [reply projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts]: Updated. Unfortunately, Cypress is no longer with me.

Comment (nsbarsukov) [reply projects/kit/src/lib/masks/time/processors/max-validation-preprocessor.ts]: > Updated. Unfortunately, Cypress is no longer with me.

I'll do it later in separate PR 👌

**Review by nsbarsukov — APPROVED** [review]

**Comment by nsbarsukov** [comment]
@demensky thanks ❤️
