### PR TITLE
fix(react): `useMaskito` should destroy Maskito instance if element is detached from the DOM

### LINKED ISSUE #2505: 🐞 - useMaskito not properly destroying if input gets destroyed
### Which package(s) are the source of the bug?

@maskito/react

### Playground Link

https://stackblitz.com/edit/vitejs-vite-oirkaspz?file=package.json,src%2FApp.tsx&terminal=dev

### Description

**Description**
When an input using `useMaskito` is conditionally rendered (e.g. toggled on/off), masking works on the first render, **fails on the second render**, works on the third, fails on the fourth, etc. The behavior alternates. See the stackblitz. At least Maskito version 3 and 5 are affected (I assume version 4 and previous versions are affected too).

**Expected behavior**
Masking should apply every time the input is rendered.

**Fix**
A working fix in our case is to `setElement` to `null` in the `useIsomorphicLayoutEffect` like:

https://github.com/taiga-family/maskito/blob/cd73d6a729068e4b301509b12def6e149a7b5d66/projects/react/src/lib/useMaskito.ts#L54-L57

```ts
useIsomorphicLayoutEffect(() => {
    if (!hostElement) {
      setElement(null); // fixes the issue
      return;
    }
```

### Maskito version

5.0.1

### Which browsers have you used?

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [x] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by HagenMorano**
Fixes #2505

### CODE REVIEW

File: projects/react/src/lib/useMaskito.ts [hunk 1]
```diff
@@ -53,6 +53,8 @@ export const useMaskito = ({
 
     useIsomorphicLayoutEffect(() => {
         if (!hostElement) {
+            setElement(null);
```
Comment (nextZed) [inline projects/react/src/lib/useMaskito.ts]: It does the trick, although the more React way would be to return a cleanup function:

```ts
    useIsomorphicLayoutEffect(() => {
        if (!hostElement) {
            return;
        }

        const elementOrPromise = elementPredicate(hostElement);

        if (isThenable(elementOrPromise)) {
          // ...
        }

        return () => {
            setElement(null); // <- here
        };
    }, [hostElement, elementPredicate, latestPredicateRef, options, latestOptionsRef]);
```

Comment (HagenMorano) [reply projects/react/src/lib/useMaskito.ts]: Agree and force pushed the change :+1:
