### PR TITLE
fix(kit): `Time` with `[step]` ignores `timeSegmentMinValues` on arrow stepping

### LINKED ISSUE #2346: 🐞 - `Time` with `[step]` ignores `timeSegmentMinValues` on arrow stepping
### Which package(s) are the source of the bug?

@maskito/react, @maskito/kit

### Playground Link

https://stackblitz.com/edit/vitejs-vite-rxdi8mxi?file=src%2FApp.tsx

### Description

timeSegmentMinValues not working when change time by arrows
Image

Image

Image

### Maskito version

3.10.1

### Which browsers have you used?

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [x] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by collin-b1**
Fixes #2346

Hello! This should fix the issue where arrow key stepping time segments would ignore `timeSegmentMinValues` and only wrap to zero. Updated the `time-step.cy.ts` test to accurately reflect hour stepping for `HH:MM AA` mode (hour wraps from 12 -> 1).

I had some troubles getting the npm test scripts to pass even in main, so let me know if anything is not working 😄

### CODE REVIEW

File: projects/kit/src/lib/masks/date-time/date-time-mask.ts [hunk 1]
```diff
@@ -125,6 +125,7 @@ export function maskitoDateTimeOptionsGenerator({
             createTimeSegmentsSteppingPlugin({
                 step: timeStep,
                 fullMode,
+                timeSegmentMinValues: DEFAULT_TIME_SEGMENT_MIN_VALUES,
```
[the remark this answers is not in the document]
Comment (nsbarsukov) [reply projects/kit/src/lib/masks/date-time/date-time-mask.ts]: @collin-b1
Probably, AI is right

[the remark this answers is not in the document]
Comment (nsbarsukov) [reply projects/kit/src/lib/masks/date-time/date-time-mask.ts]: Add Cypress tests for `DateTime` too to cover this case

File: projects/kit/src/lib/plugins/time/time-segments-stepping.ts [hunk 2]
```diff
@@ -110,10 +115,8 @@ function updateSegmentValue({
...
 
-function mod(value: number, max: number): number {
-    if (value < 0) {
-        value += Math.floor(Math.abs(value) / max + 1) * max;
-    }
+function mod(value: number, min: number, max: number): number {
+    const range = max - min;
 
-    return value % max;
+    return ((((value - min) % range) + range) % range) + min;
```
Comment (nsbarsukov) [inline projects/kit/src/lib/plugins/time/time-segments-stepping.ts:121]: Do we really need to take reminder twice if `value >= 0` & `range > 0` ?

```
(X % Y) + Y) % Y === X % Y

where 
X >= 0
Y > 0
```

**Comment by nsbarsukov** [comment]
@collin-b1 write anything inside this issue (e.g. `I'll take it`)
* https://github.com/taiga-family/maskito/issues/2346

(without your first message inside it, I cannot assign it to you – GitHub restriction)

File: projects/kit/src/lib/plugins/time/time-segments-stepping.ts (hunk 2 above)
Comment (collin-b1) [reply projects/kit/src/lib/plugins/time/time-segments-stepping.ts:121]:
```ts
function mod(value, min, max) {
    const range = max - min;

    return ((value - min) % range) + min;
}
// mod(0, 1, 13) => 0
```

```ts
function mod(value, min, max) {
    const range = max - min;

    return ((((value - min) % range) + range) % range) + min;
}
// mod(0, 1, 13) => 12
```
Shortened version works when `value >= min` but doesn't stay in `[min, max)` otherwise.

File: projects/demo-integrations/src/tests/kit/date-time/date-time-time-step.cy.ts [hunk 3]
```diff
@@ -147,4 +147,75 @@ describe('DateTime | timeStep', () => {
...
+                    .should('have.a.prop', 'selectionEnd', '22.12;'.length)
+                    .invoke('val')
+                    .should('match', /^22\.12;02:34\sPM$/);
+
+                cy.get('@input')
+                    .type('{downArrow}'.repeat(4))
+                    .should('have.a.prop', 'selectionStart', '22.12;'.length)
+                    .should('have.a.prop', 'selectionEnd', '22.12;'.length)
+                    .invoke('val')
+                    .should('match', /^22\.12;10:34\sPM$/);
```
Comment (collin-b1) [inline projects/demo-integrations/src/tests/kit/date-time/date-time-time-step.cy.ts]: Did regex matching because have.value would inconsistently not work due to non-breaking spaces vs regular spaces.

File: projects/kit/src/lib/masks/date-time/date-time-mask.ts [hunk 4]
```diff
@@ -125,8 +125,8 @@ export function maskitoDateTimeOptionsGenerator({
             createTimeSegmentsSteppingPlugin({
                 step: timeStep,
                 fullMode,
-                timeSegmentMinValues: DEFAULT_TIME_SEGMENT_MIN_VALUES,
-                timeSegmentMaxValues: DEFAULT_TIME_SEGMENT_MAX_VALUES,
```
Comment (collin-b1) [inline projects/kit/src/lib/masks/date-time/date-time-mask.ts:128]: Both of these needed to be updated to support proper min/max stepping with meridiem.

File: projects/kit/src/lib/plugins/time/time-segments-stepping.ts (hunk 2 above)
Comment (nsbarsukov) [reply projects/kit/src/lib/plugins/time/time-segments-stepping.ts:121]: Thanks for clarification!
Let's leave it as is

File: projects/demo-integrations/src/tests/kit/date-time/date-time-time-step.cy.ts (hunk 3 above)
Comment (nsbarsukov) [reply projects/demo-integrations/src/tests/kit/date-time/date-time-time-step.cy.ts]: You could just directly use non-breaking space here

In the same way as here:
https://github.com/taiga-family/maskito/blob/7a51702361237a41cd9bbdcdbb8e46d0bfa2e4bc/projects/demo-integrations/src/tests/kit/time/time-meridiem.cy.ts#L20

Comment (nsbarsukov) [reply projects/demo-integrations/src/tests/kit/date-time/date-time-time-step.cy.ts]: And replace all occurrences of
```ts
.invoke('val')
.should('match', /.../);
```

with 
```ts
.should('have.value', '...')
```

File: projects/demo-integrations/src/tests/kit/date-time/date-time-time-step.cy.ts [hunk 5]
```diff
@@ -147,4 +147,75 @@ describe('DateTime | timeStep', () => {
...
+                    .type('1234p')
+                    .invoke('val')
+                    .should('match', /^22\.12;12:34\sPM$/);
+
+                cy.get('@input')
+                    .should('have.a.prop', 'selectionStart', '22.12;12:34 PM'.length)
+                    .should('have.a.prop', 'selectionEnd', '22.12;12:34 PM'.length);
+
+                cy.get('@input')
+                    .type('{home}')
```
Comment (nsbarsukov) [inline projects/demo-integrations/src/tests/kit/date-time/date-time-time-step.cy.ts]:
```suggestion
                    .type('{moveToStart}')
```

(it is just more self-descriptive way to do the same)
https://docs.cypress.io/api/commands/type#Arguments

File: projects/demo-integrations/src/tests/kit/date-time/date-time-time-step.cy.ts [hunk 6]
```diff
@@ -147,4 +147,75 @@ describe('DateTime | timeStep', () => {
...
+            it('increments and decrements minutes in AM/PM mode correctly', () => {
+                cy.get('@input').type('1234a');
+                cy.get('@input')
+                    .invoke('val')
+                    .should('match', /^22\.12;12:34\sAM$/);
+
+                cy.get('@input')
+                    .should('have.a.prop', 'selectionStart', '22.12;12:34 AM'.length)
+                    .should('have.a.prop', 'selectionEnd', '22.12;12:34 AM'.length)
+                    .type('{leftArrow}{leftArrow}{leftArrow}{upArrow}{upArrow}');
```
Comment (nsbarsukov) [inline projects/demo-integrations/src/tests/kit/date-time/date-time-time-step.cy.ts]:
```suggestion
                    .type('{leftArrow}'.repeat(3))
                    .type('{upArrow}'.repeat(2));
```

**Review by nsbarsukov — APPROVED** [review]
