### PR TITLE
fix(core): incorrect handle of paste event for `<input />` with `maxlength` attribute

### LINKED ISSUE #1993: 🐞 - Incorrect handle of paste event for `<input />` with `maxlength` attribute
### Which package(s) are the source of the bug?

@maskito/core

### Playground Link

https://stackblitz.com/edit/max-length-paste-bug

### Description

```html
<input maxlength="3" placeholder="Paste number with >3 digits" />
```

Paste
```
123456789
```

#### Without Maskito

Textfield contains `123`.

#### With Maskito

**Expected behavior**: textfield contains `123`.
**Actual behavior**: textfield is empty.

### Maskito version

3.3.0

### Which browsers have you used?

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
Fixes #1993

### CODE REVIEW

File: projects/core/src/lib/mask.ts [hunk 1]
```diff
@@ -318,14 +318,12 @@ export class Maskito extends MaskHistory {
                 initialElementState.value.slice(to),
             selection: [from + data.length, from + data.length],
```
Comment (splincode) [inline projects/core/src/lib/mask.ts:319]: why not 

```ts
const newPossibleState: ElementState = this.clampState({
            value:
                initialState.value.slice(0, initialFrom) +
                initialState.value.slice(initialTo),
            selection: [initialFrom, initialFrom],
        });
```

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]

File: projects/core/src/lib/mask.ts (hunk 1 above)
Comment (nsbarsukov) [reply projects/core/src/lib/mask.ts:319]: Variable `newPossibleState` is used twice in this method.
The last usage:
```js
newPossibleState.value.length > maxLength
```

We should use **un**clampled version for this check.
