### PR TITLE
fix(kit): `maskitoStringifyNumber` supports extremal exponent values

### LINKED ISSUE #2462: 🐞 - `maskitoStringifyNumber` should handle `1e24` properly
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/pqtbomhy?file=index.ts

### Description

```ts
maskitoStringifyNumber(1e24, {}) // 124
maskitoStringifyNumber(10n ** 24n, {}) // 1 000 000 000 000 000 000 000 000
```

The expected output of `maskitoStringifyNumber(1e24, {})` is `1 000 000 000 000 000 000 000 000`, however it currently returns `124`. Although it exceeds `Number.MAX_SAFE_INTEGER`, it should still produce appropriate results.

### Maskito version

5.0.0

### Which browsers have you used?

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
Fixes #2462

### CODE REVIEW

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts [hunk 1]
```diff
@@ -5,17 +5,44 @@
  * @return string representation of a number
  */
 export function stringifyNumberWithoutExp(value: bigint | number): string {
+    if (typeof value === 'bigint') {
+        return value.toString();
+    }
+
     const valueAsString = String(value);
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts:42]:
```suggestion
export function stringifyNumberWithoutExp(value: bigint | number): string {
    const valueAsString = String(value);

    if (typeof value === 'bigint') {
        return valueAsString;
    }
```

Comment (nsbarsukov) [reply projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts:42]: Or even 
```ts
const valueAsString = String(value);
const [numberPart = '', expPart] = valueAsString.split('e');

if (typeof value === 'bigint' || !expPart) {
    return valueAsString;
}
```

Comment (nsbarsukov) [reply projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts:42]: Or even without `typeof value === 'bigint'` (big int will never have `expPart`)

```ts
const valueAsString = String(value);
const [numberPart = '', expPart] = valueAsString.split('e');

if (!expPart) {
    return valueAsString;
}
```

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts [hunk 2]
```diff
@@ -5,17 +5,44 @@
...
+
+    if (!expPart) {
+        return valueAsString;
+    }
+
+    const isNegativeExp = expPart.startsWith('-');
+    const exp = Math.abs(Number(expPart));
+
+    if (!isNegativeExp) {
+        return value.toLocaleString('fullwide', {useGrouping: false});
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: Why `fullwide` is required ? Could you provide example when it does not work without it ?

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts [hunk 3]
```diff
@@ -5,17 +5,44 @@
...
+    }
+
+    const isNegativeValue = numberPart.startsWith('-');
+    const unsignedNumberPart = isNegativeValue ? numberPart.slice(1) : numberPart;
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: Could we just use `Math.abs` ?

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts (hunk 1 above)
Comment (splincode) [reply projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts:42]: fixed

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts [hunk 4]
```diff
@@ -1,21 +1,59 @@
...
+    if (!exponent) {
+        return valueAsString;
+    }
+
+    if (!exponent.startsWith('-')) {
+        return value.toLocaleString([], {useGrouping: false});
+    }
+
+    const sign = numberPart.startsWith('-') ? '-' : '';
+    const unsignedNumberPart = sign ? numberPart.slice(1) : numberPart;
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: Is it better ? 🤔 


```suggestion
    let [, sign, unsignedNumberPart] = '-123.45'.match(/^(-)(.*)/)
```

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts [hunk 5]
```diff
@@ -1,21 +1,59 @@
...
+    const parts = unsignedNumberPart.split('.');
+    const intPart = parts[0] ?? '';
+    const fracPart = parts[1] ?? '';
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]:
```suggestion
    const [intPart = '', fracPart = ''] = unsignedNumberPart.split('.');
```

Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: Maskito repo has internal heler `toNumberParts` utility.
Could it used here ?

```ts
const {minus, integerPart, decimalPart} = toNumberParts(numberPart, {
        minusSign: CHAR_HYPHEN,
        minusPseudoSigns: [],
        prefix: '',
        postfix: '',
        decimalSeparator: '.',
        decimalPseudoSeparators: [],
        maximumFractionDigits: Infinity,
    });
```

**Review by nsbarsukov — COMMENTED** [review]
Fix Lint job

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts (hunk 2 above)
Comment (splincode) [reply projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: fixed

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts (hunk 3 above)
Comment (splincode) [reply projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: fixed

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts (hunk 4 above)
Comment (splincode) [reply projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: fixed

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts (hunk 5 above)
Comment (splincode) [reply projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: fixed

Comment (splincode) [reply projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: fixed

File: projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts [hunk 6]
```diff
@@ -1,21 +1,68 @@
...
+        result = `0.${'0'.repeat(totalZeros)}${digits}`;
+    } else {
+        const index = integerPart.length - shift;
 
-        valueWithoutExp = value.toFixed(decimalDigits);
+        result = `${digits.slice(0, index)}.${digits.slice(index)}`;
     }
 
-    return valueWithoutExp;
+    return minus ? `-${result}` : result;
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: `minus` already contains hyphen if negative and empty string – if positive

```suggestion
    return minus + result;
```

Comment (splincode) [reply projects/kit/src/lib/masks/number/utils/stringify-number-without-exp.ts]: fixed
