### PR TITLE
fix(phone): `Phone` preserves previously entered digits on new digits paste

### LINKED ISSUE #2445: 🐞 - Non-strict phone mask erases country code when pasting phone number
### Which package(s) are the source of the bug?

@maskito/phone

### Playground Link

https://maskito.dev/addons/phone/#non-strict

### Description

When using the non-strict phone mask, entering the country code +7 and then pasting the remaining part of the phone number (e.g. 9773630125) results in the +7 being overwritten. The input displays +977 36 30125 instead of preserving the original country code.

Expected behavior:
The pasted number should be appended after the entered +7, resulting in a correctly formatted number such as +7 (977) 363-01-25.

Actual behavior:
The +7 prefix is erased and incorrectly replaced with +977.

Reproduction steps:

1. Use the non-strict phone mask (see: [https://maskito.dev/addons/phone#non-strict ](https://maskito.dev/addons/phone#non-strict)).
2. Manually type +7.
3. Paste 9773630125 into the field.
4. Observe that +7 is replaced and the result becomes +977 36 30125

### Maskito version

4.0.1

### Which browsers have you used?

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by DevWedeloper**
Fixes #2445

### CODE REVIEW

File: projects/phone/src/lib/masks/phone/phone-mask-strict.ts [hunk 1]
```diff
@@ -52,6 +53,7 @@ export function maskitoPhoneStrictOptionsGenerator({
         preprocessors: [
             cutInitCountryCodePreprocessor({countryIsoCode, metadata}),
             validatePhonePreprocessorGenerator({prefix, countryIsoCode, metadata}),
+            normalizePhonePreprocessorGenerator({prefix, countryIsoCode, metadata}),
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/phone-mask-strict.ts]: It fixes #2445 but introduces new bug for cases with national trunk prefix.

After merging this PR, rebase your branch and run tests from `projects/demo-integrations/src/tests/addons/phone/phone-national-trunk-prefix.cy.ts`. Two tests will fail
* https://github.com/taiga-family/maskito/pull/2486

Comment (nsbarsukov) [reply projects/phone/src/lib/masks/phone/phone-mask-strict.ts]:
```
➜ cd projects/demo-integrations && cypress run --spec **/phone-national-trunk-prefix.cy.ts  

# [...]

  Phone | Replaces national trunk prefix by international one on paste
    AU | 0 as national trunk prefix
      1) [strict=false] Paste 0733333333 => +61 7 3333-3333
      ✓ [strict=true] Paste 0733333333 => +61 7 3333-3333 (278ms)
    RU | 8 as national trunk prefix
      2) [strict=false] Paste 89123456789 => +7 912 345-67-89
      ✓ [strict=true] Paste 89123456789 => +7 912 345-67-89 (240ms)


  2 passing (22s)
  2 failing

  1) Phone | Replaces national trunk prefix by international one on paste
       AU | 0 as national trunk prefix
         [strict=false] Paste 0733333333 => +61 7 3333-3333:

      Timed out retrying after 10000ms
      + expected - actual

      -'+0733333333'
      +'+61 7 3333-3333'                                        
                                                                                                                                                                                   
  2) Phone | Replaces national trunk prefix by international one on paste
       RU | 8 as national trunk prefix
         [strict=false] Paste 89123456789 => +7 912 345-67-89:

      Timed out retrying after 10000ms
      + expected - actual

      -'+89123456789'
      +'+7 912 345-67-89'
                                                          
====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  phone-national-trunk-prefix.cy.ts        00:21        4        2        2        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:21        4        2        2        -        -  

```

File: projects/demo-integrations/src/tests/addons/phone/phone-non-strict.cy.ts [hunk 2]
```diff
@@ -172,9 +172,17 @@ describe('Phone', () => {
 
         describe('Pasting numbers', () => {
             it('should not cut the last digit when pasting', () => {
+                openCountry('US');
```
Comment (nsbarsukov) [inline projects/demo-integrations/src/tests/addons/phone/phone-non-strict.cy.ts]: Actually, it is a regression.
We cannot just ignore it and change test case.

**Non-strict** mask should allow any country. Even if optional parameter `countryIso` is set to another country.

Explore more:
https://maskito.dev/addons/phone#non-strict

https://github.com/user-attachments/assets/02003a31-1226-426c-a6e8-b231c3409603

File: projects/demo-integrations/src/tests/addons/phone/phone-non-strict.cy.ts [hunk 3]
```diff
@@ -172,9 +172,17 @@ describe('Phone', () => {
...
+
                 cy.get('@input').paste('12125552365');
                 cy.get('@input').should('have.value', '+1 212 555-2365');
             });
+
+            it('should merge pasted numbers with existing input', () => {
+                cy.get('@input').clear().type('+6488');
+                cy.get('@input').paste('85584567');
+                cy.get('@input').should('have.value', '+64 888 558-4567');
```
Comment (nsbarsukov) [inline projects/demo-integrations/src/tests/addons/phone/phone-non-strict.cy.ts]:
```suggestion
                cy.get('@input')
                    .type('+6488')
                    .paste('85584567')
                    .should('have.value', '+64 888 558-4567')
```

File: projects/demo-integrations/src/tests/addons/phone/phone-strict.cy.ts [hunk 4]
```diff
@@ -64,4 +64,22 @@ describe('Phone [strict]=true', () => {
...
+            cy.get('#demo-content input')
+                .should('be.visible')
+                .first()
+                .focus()
+                .should('have.value', '+7 ')
+                .as('input');
+        });
+
+        it('should merge pasted numbers with existing input', () => {
+            cy.get('@input').clear().type('+987');
```
Comment (nsbarsukov) [inline projects/demo-integrations/src/tests/addons/phone/phone-strict.cy.ts]: Why plus sign ?
And use chaining style here too

File: projects/phone/src/lib/masks/phone/processors/validate-phone-preprocessor.ts [hunk 5]
```diff
@@ -1,10 +1,6 @@
 import type {MaskitoPreprocessor} from '@maskito/core';
 import type {CountryCode, MetadataJson} from 'libphonenumber-js/core';
-import {
-    AsYouType,
-    parsePhoneNumber,
-    validatePhoneNumberLength,
-} from 'libphonenumber-js/core';
+import {AsYouType} from 'libphonenumber-js/core';
 
 export function validatePhonePreprocessorGenerator({
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/validate-phone-preprocessor.ts]: If now this preprocessor is responsible only for browser autofill (it is good news) – let's rename `validatePhonePreprocessorGenerator` => `browserAutofillPreprocessorGenerator`

File: projects/phone/src/lib/masks/phone/processors/normalize-strict-phone-preprocessor.ts [hunk 6]
```diff
@@ -0,0 +1,41 @@
+import type {MaskitoPreprocessor} from '@maskito/core';
+import type {CountryCode, MetadataJson} from 'libphonenumber-js/core';
+import {parsePhoneNumber} from 'libphonenumber-js/core';
+
+export function normalizeStrictPhonePreprocessorGenerator({
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/normalize-strict-phone-preprocessor.ts]: The same case here: `normalizeStrictPhonePreprocessorGenerator` => `pasteStrictPhonePreprocessorGenerator`

File: projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+        const {selection, value} = elementState;
+
+        // handle paste of a number when input is empty
+        if (data.length > 2 && value === '') {
+            const phone = (() => {
+                if (!data.startsWith(prefix) && countryIsoCode) {
+                    try {
+                        const normalized = `+${data}`;
+
+                        return parsePhoneNumber(normalized, countryIsoCode, metadata);
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts]: This constant is used only once? Just inline it then


```suggestion
                        return parsePhoneNumber(`+${data}`, countryIsoCode, metadata);
```

File: projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts [hunk 8]
```diff
@@ -0,0 +1,47 @@
+import type {MaskitoPreprocessor} from '@maskito/core';
+import type {CountryCode, MetadataJson} from 'libphonenumber-js/core';
+import {parsePhoneNumber} from 'libphonenumber-js/core';
+
+export function normalizeNonStrictPhonePreprocessorGenerator({
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts]: `normalizeNonStrictPhonePreprocessorGenerator` => `pasteNonStrictPhonePreprocessorGenerator`

File: projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts [hunk 9]
```diff
@@ -0,0 +1,47 @@
...
+
+                        return parsePhoneNumber(normalized, countryIsoCode, metadata);
+                    } catch {
+                        // fallback: try original data without normalization
+                        return parsePhoneNumber(data, countryIsoCode, metadata);
+                    }
+                } else {
+                    return parsePhoneNumber(data, metadata);
+                }
+            })();
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts]: Why IIFE is used here ? Just create local function (without export) `parse` in this file

File: projects/phone/src/lib/masks/phone/processors/paste-strict-phone-preprocessor.ts [hunk 10]
```diff
@@ -0,0 +1,41 @@
...
+    countryIsoCode?: CountryCode;
+    metadata: MetadataJson;
+}): MaskitoPreprocessor {
+    return ({elementState, data}) => {
+        const {selection, value} = elementState;
+        const [from] = selection;
+        const selectionIncludesPrefix = from < prefix.length;
+
+        // handle paste of a number when input contains only the prefix
+        if (data.length > 2 && value.trim() === prefix.trim()) {
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/paste-strict-phone-preprocessor.ts:22]: Now It is easy to get console error.

Just type any non-digit input and you will get error:
```
zone.js:1191 Uncaught ParseError2: NOT_A_NUMBER
    at parse (parse.js:86:13)
    at parsePhoneNumberWithError (parsePhoneNumberWithError_.js:55:10)
    at parsePhoneNumberWithError2 (parsePhoneNumberWithError.js:8:10)
    at normalize-strict-phone-preprocessor.ts:23:19
    at pipe.ts:23:41
    at Array.reduce (<anonymous>)
    at Maskito.preprocessor (pipe.ts:22:20)
    at Maskito.handleInsert (mask.ts:293:64)
    at HTMLInputElement.<anonymous> (mask.ts:130:33)
    at _ZoneDelegate.invokeTask (zone.js:431:33)
```

File: projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts [hunk 11]
```diff
@@ -0,0 +1,47 @@
...
+                    try {
+                        const normalized = `+${data}`;
+
+                        return parsePhoneNumber(normalized, countryIsoCode, metadata);
+                    } catch {
+                        // fallback: try original data without normalization
+                        return parsePhoneNumber(data, countryIsoCode, metadata);
+                    }
+                } else {
+                    return parsePhoneNumber(data, metadata);
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts]: I'm not sure we really need this level of complexity. Do we strictly need different logic for **strict** and **non-strict** mask?

Perhaps we could just augment the previous solution with: `if(data && (!value || value === prefix)) {...}`
https://github.com/taiga-family/maskito/blob/c90bca2c2f0f3bc3746a2559fc84bd688075c1be/projects/phone/src/lib/masks/phone/processors/validate-phone-preprocessor.ts#L105-L141

P.S. move logic about browser autofill and logic about paste event into different preprocessors are good idea. We can still implement it, yep

**Review by nsbarsukov — COMMENTED** [review]
Rebase your branch and fix merge conflicts

File: projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts (hunk 11 above)
Comment (DevWedeloper) [reply projects/phone/src/lib/masks/phone/processors/normalize-non-strict-phone-preprocessor.ts]: > Do we strictly need different logic for strict and non-strict mask?

It needs separate logic, with the existing one, any paste that doesn't start with + sign would reset the whole input.

File: projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts [hunk 12]
```diff
@@ -0,0 +1,62 @@
...
+                metadata,
+            });
+
+            const {number} = phone;
+
+            return {
+                elementState: {
+                    selection,
+                    value: '',
+                },
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts]: You already checked that `value` is empty above

```suggestion
        if (data.length > 2 && value === '') {
            const phone = parsePhone({
                data,
                prefix,
                countryIsoCode,
                metadata,
            });

            const {number} = phone;

            return {
                elementState,
```

File: projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts [hunk 13]
```diff
@@ -0,0 +1,62 @@
...
+    metadata,
+}: {
+    prefix: string;
+    countryIsoCode?: CountryCode;
+    metadata: MetadataJson;
+}): MaskitoPreprocessor {
+    return ({elementState, data}) => {
+        const {selection, value} = elementState;
+
+        // handle paste of a number when input is empty
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts]: excessive code comment

File: projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts [hunk 14]
```diff
@@ -0,0 +1,62 @@
...
+            return {
+                elementState: {
+                    selection,
+                    value: '',
+                },
+                data: number,
+            };
+        }
+
+        return {elementState};
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts]:
```ts
export function pasteNonStrictPhonePreprocessorGenerator({
    prefix,
    countryIsoCode,
    metadata,
}: {
    prefix: string;
    countryIsoCode?: CountryCode;
    metadata: MetadataJson;
}): MaskitoPreprocessor {
    return ({elementState, data}) => {
        return {
            elementState,
            data:
                data.length > 2 && elementState.value === ''
                    ? parsePhone({
                          data,
                          prefix,
                          countryIsoCode,
                          metadata,
                      }).number
                    : data,
        };
    };
}
```

File: projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts [hunk 15]
```diff
@@ -0,0 +1,62 @@
...
+
+export function pasteNonStrictPhonePreprocessorGenerator({
+    prefix,
+    countryIsoCode,
+    metadata,
+}: {
+    prefix: string;
+    countryIsoCode?: CountryCode;
+    metadata: MetadataJson;
+}): MaskitoPreprocessor {
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts]:
```suggestion
}: : Pick<Required<MaskitoPhoneParams>, 'countryIsoCode' | 'metadata'> & {
    prefix: string;
}): MaskitoPreprocessor {
```

File: projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts [hunk 16]
```diff
@@ -0,0 +1,12 @@
+import type {MaskitoPreprocessor} from '@maskito/core';
+
+export function sanitizePhonePreprocessorGenerator(): MaskitoPreprocessor {
+    return ({elementState, data}) => {
+        const sanitizedData = data.replaceAll(/[^\d+]/g, '');
+
+        return {
+            elementState,
+            data: sanitizedData,
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts]:
```suggestion
        return {
            elementState,
            data: data.replaceAll(/[^\d+]/g, ''),
```

File: projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts [hunk 17]
```diff
@@ -0,0 +1,12 @@
...
+        };
+    };
+}
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts]:
```ts
export const sanitizePreprocessor: MaskitoPreprocessor = ({
    elementState,
    data,
}) => ({
    elementState,
    data: data.replaceAll(/[^\d+]/g, ''),
});
```

File: projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts (hunk 15 above)
Comment (DevWedeloper) [reply projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts]: I can't use required here as `countryIsoCode` can be undefined in non-strict mask

Comment (nsbarsukov) [reply projects/phone/src/lib/masks/phone/processors/paste-non-strict-phone-preprocessor.ts]: My mistake, let's use without `Required`

```ts
Pick<MaskitoPhoneParams, 'countryIsoCode' | 'metadata'> & {
    prefix: string;
}
```

File: projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts [hunk 18]
```diff
@@ -0,0 +1,8 @@
+import type {MaskitoPreprocessor} from '@maskito/core';
+
+export const sanitizePreprocessor =
+    (): MaskitoPreprocessor =>
+    ({elementState, data}) => ({
+        elementState,
+        data: (data ?? '').replaceAll(/[^\d+]/g, ''),
+    });
```
Comment (nsbarsukov) [inline projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts]: Check my previous comment again

https://github.com/taiga-family/maskito/pull/2481#discussion_r2758127446

**Review by vladimirpotekhin — APPROVED** [review]

**Comment by nsbarsukov** [comment]
@DevWedeloper Hello! Could you please resolve the remaining threads so we can finally merge this PR?

File: projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts (hunk 18 above)
Comment (nsbarsukov) [reply projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts]: @DevWedeloper this thread is still unresolved


```ts
export const sanitizePreprocessor: MaskitoPreprocessor = ({
    elementState,
    data,
}) => ({
        elementState,
        data: (data ?? '').replaceAll(/[^\d+]/g, ''),
    });
```

**Comment by DevWedeloper** [comment]
Apologies for the delay, it should be all good now

**Comment by nsbarsukov** [comment]
> Apologies for the delay, it should be all good now

@DevWedeloper 
Still not resolved https://github.com/taiga-family/maskito/pull/2481#discussion_r2791742502

Are you sure that you don't forget to use `git push` ?

File: projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts (hunk 18 above)
Comment (DevWedeloper) [reply projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts]: Hi just to clarify, are you saying I should use this syntax? It's not allowed, as I'm getting this error

> Type '{ elementState: ElementState; data?: string | undefined; }' is not assignable to type 'MaskitoPreprocessor'.
  Type '{ elementState: ElementState; data?: string | undefined; }' provides no match for the signature '(_: { elementState: ElementState; data: string; }, actionType: "deleteBackward" | "deleteForward" | "insert" | "validation"): { elementState: ElementState; data?: string | undefined; }'.ts(2322)

Comment (nsbarsukov) [reply projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts]: Have you also updated `projects/phone/src/lib/masks/phone/phone-mask-non-strict.ts` and `projects/phone/src/lib/masks/phone/phone-mask-strict.ts` after making this change ?

```diff
preprocessors: [
-    sanitizePreprocessor(),
+    sanitizePreprocessor,
    // [...]
],
```

Comment (DevWedeloper) [reply projects/phone/src/lib/masks/phone/processors/sanitize-phone-preprocessor.ts]: Gotcha, let me correct that
