### PR TITLE
fix(core): don't execute `setSelectionRange` if element is not focused

### LINKED ISSUE #929: 🐞 - No need to execute `setSelectionRange` if element is not focused
### Which package(s) are the source of the bug?

@maskito/core, @maskito/kit, @maskito/react

### Playground Link

https://stackblitz.com/edit/stackblitz-starters-4s7lyp?file=src%2FNumberInput.tsx

### Description

When I add a postfix in maskitoNumberOptionsGenerator (but I think it also appends if I add a postfix manually through postProcess), the input gains focus without any action.

I have only seen this in the mobile version because the keyboard opens automatically. You can try it using the StackBlitz link; go to the application link on a mobile device.

### Maskito version

1.9.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

Closes #929

### CODE REVIEW

File: projects/core/src/lib/utils/dom/get-focused.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@
  *
  * @return element or null
  */
-export function getFocused({activeElement}: Document): Element | null {
+export function maskitoGetFocused({activeElement}: Document): Element | null {
```
Comment (waterplea) [inline projects/core/src/lib/utils/dom/get-focused.ts:6]: Why do we expose it now?

**Review by waterplea — APPROVED** [review]

File: projects/core/src/lib/utils/dom/get-focused.ts (hunk 1 above)
Comment (nsbarsukov) [reply projects/core/src/lib/utils/dom/get-focused.ts:6]: I need this utility in both `@maskito/core` & `@maskito/kit` packages (

Comment (nsbarsukov) [reply projects/core/src/lib/utils/dom/get-focused.ts]: @waterplea review again, please

**Review by waterplea — APPROVED** [review]
