### PR TITLE
fix(kit): `Number` has problems when prefix/postfix includes `decimalSeparator` symbol

### LINKED ISSUE #703: 🐞 - Number mask from kit has problems with processing postfix with dot
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/hyw39y?file=index.ts,mask.ts

### Description

1. Open https://stackblitz.com/edit/hyw39y?file=index.ts,mask.ts
2. Try to type 123 into input

**Expected:**
Number and postfix is separated.
Value is '123 руб.'

**Actual:**
Postfix probably identified as a part of number.
Value is '23 1ру. руб'

This workaround currently works good:
https://stackblitz.com/edit/hyw39y-zkwvwb?file=index.ts,mask.ts

### Maskito version

1.9.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by aktanoff**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behaviour?

Closes #703 

## What is the new behaviour?

Added new utility `extractPrefixAndPostfix`, which extracts prefix and postfix to separate variables, and extracts cleanValue without prefix and postfix.

Used it in methods, which working with decimalSeparator to avoid decimalSeparator false matching dot in prefix and postfix.

There also many things to rethink, i have 2 more ways to fix this bug:
1. Remove prefix and postfix in first preprocessor, and add it in last postprocessor. But we still will be needed in prefix and postfix arguments inside `maskitoParseNumber`
2. Add some zerowidth symbol to separate prefix and postfix, and then we will not have to pass this parameters in any method, even in `maskitoParseNumber`

I will add tests after basic review

### CODE REVIEW

File: projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts [hunk 1]
```diff
@@ -22,21 +22,21 @@ export function createThousandSeparatorPostprocessor({
         return identity;
     }
 
-    const prefixReg = new RegExp(`^${escapeRegExp(prefix)}${CHAR_MINUS}?`);
-    const postfixReg = new RegExp(`${escapeRegExp(postfix)}$`);
     const isAllSpaces = (...chars: string[]): boolean => chars.every(x => /\s/.test(x));
 
     return ({value, selection}) => {
-        const [integerPart, decimalPart = ''] = value.split(decimalSeparator);
+        const {cleanValue, extractedPostfix, extractedPrefix} = extractPrefixAndPostfix({
```
Comment (aktanoff) [inline projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts:28]: now we firstly removing prefix and postfix from value, and then splitting cleanValue to numberParts

File: projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts [hunk 2]
```diff
@@ -22,21 +22,21 @@ export function createThousandSeparatorPostprocessor({
...
+            shouldExtractMinus: true,
+        });
+
+        const [integerPart, decimalPart = ''] = cleanValue.split(decimalSeparator);
         const [initialFrom, initialTo] = selection;
         let [from, to] = selection;
 
-        const cleanIntegerPart = integerPart
-            .replace(prefixReg, '')
-            .replace(postfixReg, '');
```
Comment (aktanoff) [inline projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts:36]: in previous variation postfix could be in decimalPart, but this case not handled

**Comment by nsbarsukov** [comment]
Thanks for your PR!

I will try to explore your solution soon (tomorrow or after January 9th).

Actually, I don't want to expand public API of `maskitoParseNumber` 🤔 
Maybe there is another solution ? I will investigate it and I'll be back with feedback.

File: projects/kit/src/lib/masks/number/utils/parse-number.ts [hunk 3]
```diff
@@ -1,14 +1,22 @@
 import {CHAR_EM_DASH, CHAR_EN_DASH, CHAR_HYPHEN, CHAR_MINUS} from '../../../constants';
 import {escapeRegExp} from '../../../utils';
+import {extractPrefixAndPostfix} from './extract-prefix-and-postfix';
 
 export function maskitoParseNumber(
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/utils/parse-number.ts:5]: I've update utility `maskitoParseNumber` in this PR https://github.com/taiga-family/maskito/pull/874
I think we could revert changes for this file.

As for **postfix with decimal separator**, `maskitoParseNumber` can parse it now without additional argument:
```ts
maskitoParseNumber('1 000.42 lbs.') // 1 000.42
```

___

As for **prefix with decimal separator**, `maskitoParseNumber` can parse it now without additional argument too:
```ts
maskitoParseNumber('lbs. 1 000.42') // 1 000.42
```

The **only exception** – when prefix is ended with decimal separator and does not separated from number by space or any other characters.
```ts
maskitoParseNumber('lbs. .42') // 0.42
maskitoParseNumber('lbs.42') // 42 or 0.42 ?
```

I think it very rare case and we can add simple workaround for it.
I will explain everything in separate comment.

Comment (nsbarsukov) [reply projects/kit/src/lib/masks/number/utils/parse-number.ts:5]: I think for this rare case we can automatically pad prefix with zero-width space.

**projects/kit/src/lib/constants/unicode-characters.ts:**
```ts
export const CHAR_ZERO_WIDTH_SPACE = '\u200B';
```


**projects/kit/src/lib/masks/number/number-mask.ts:**
```ts
export function maskitoNumberOptionsGenerator({
    decimalSeparator = '.',
    prefix = '',
    // [...]
}): Required<MaskitoOptions> {
    const safePrefix = prefix.endsWith(decimalSeparator)
        ? `${prefix}${CHAR_ZERO_WIDTH_SPACE}`
        : prefix;
    // [...]
}
```

File: projects/kit/src/lib/masks/number/number-mask.ts
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/number-mask.ts:1]: Rebase the branch and enable some tests from this PR https://github.com/taiga-family/maskito/pull/875, please:

* Replace `xdescribe` with `describe`:
https://github.com/taiga-family/maskito/blob/dc3df4e1c93f0169e95ab12bbf3eb17a4ecfed0d/projects/kit/src/lib/masks/number/tests/number-mask.spec.ts#L87-L88

* Delete `.skip`
https://github.com/taiga-family/maskito/blob/dc3df4e1c93f0169e95ab12bbf3eb17a4ecfed0d/projects/demo-integrations/src/tests/component-testing/number-postfix/number-postfix-with-point.cy.ts#L38-L39
https://github.com/taiga-family/maskito/blob/dc3df4e1c93f0169e95ab12bbf3eb17a4ecfed0d/projects/demo-integrations/src/tests/component-testing/number-postfix/number-postfix-with-point.cy.ts#L55-L56

File: projects/kit/src/lib/masks/number/plugins/leading-zeroes-validation.plugin.ts [hunk 4]
```diff
@@ -22,13 +30,23 @@ export function createLeadingZeroesValidationPlugin(
...
+            const {cleanValue, extractedPostfix, extractedPrefix} =
+                extractPrefixAndPostfix({
                     value: element.value,
-                    selection: DUMMY_SELECTION,
-                },
-                {value: '', selection: DUMMY_SELECTION},
-            ).value;
+                    prefix,
+                    postfix,
+                });
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/plugins/leading-zeroes-validation.plugin.ts:38]: Should it be done inside `createLeadingZeroesValidationPostprocessor` ? 🤔

File: projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts [hunk 5]
```diff
@@ -22,21 +22,21 @@ export function createThousandSeparatorPostprocessor({
...
-    const postfixReg = new RegExp(`${escapeRegExp(postfix)}$`);
     const isAllSpaces = (...chars: string[]): boolean => chars.every(x => /\s/.test(x));
 
     return ({value, selection}) => {
-        const [integerPart, decimalPart = ''] = value.split(decimalSeparator);
+        const {cleanValue, extractedPostfix, extractedPrefix} = extractPrefixAndPostfix({
+            value,
+            prefix,
+            postfix,
+            shouldExtractMinus: true,
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts:32]: Is it the only place where we use `shouldExtractMinus` ? 🤔 

I think we should **not** incapsulate this logic inside `extractPrefixAndPostfix` and we can extract the possible minus sign independently by separate RegExp inside this file.

File: projects/kit/src/lib/masks/number/utils/extract-prefix-and-postfix.ts [hunk 6]
```diff
@@ -0,0 +1,29 @@
+import {CHAR_MINUS} from '../../../constants';
+import {escapeRegExp} from '../../../utils';
+
+export function extractPrefixAndPostfix({
```
[the remark this answers is not in the document]
Comment (aktanoff) [reply projects/kit/src/lib/masks/number/utils/extract-prefix-and-postfix.ts:4]: yeah, that looks better

File: projects/kit/src/lib/masks/number/plugins/leading-zeroes-validation.plugin.ts [hunk 7]
```diff
@@ -10,25 +11,42 @@ const DUMMY_SELECTION = [0, 0] as const;
...
         'blur',
         element => {
-            const newValue = dropRepeatedLeadingZeroes(
-                {
-                    value: element.value,
-                    selection: DUMMY_SELECTION,
-                },
-                {value: '', selection: DUMMY_SELECTION},
-            ).value;
+            const {cleanValue, extractedPostfix, extractedPrefix} = extractAffixes(
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/plugins/leading-zeroes-validation.plugin.ts:35]: `createLeadingZeroesValidationPostprocessor` can handle cases with prefix/postfix now. Should we drop these lines now ?

File: projects/kit/src/lib/masks/number/processors/decimal-zero-padding-postprocessor.ts [hunk 8]
```diff
@@ -1,7 +1,8 @@
 import {MaskitoPostprocessor} from '@maskito/core';
 
-import {escapeRegExp, identity} from '../../../utils';
+import {identity} from '../../../utils';
 import {maskitoParseNumber} from '../utils';
+import {extractAffixes} from '../utils/extract-affixes';
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/processors/decimal-zero-padding-postprocessor.ts:5]: Add export of `extractAffixes` to `projects/kit/src/lib/utils/index.ts`

File: projects/kit/src/lib/masks/number/processors/repeated-decimal-separator-preprocessor.ts [hunk 9]
```diff
@@ -1,23 +1,33 @@
...
+    prefix,
+    postfix,
+}: {
+    decimalSeparator: string;
+    prefix: string;
+    postfix: string;
+}): MaskitoPreprocessor {
     return ({elementState, data}) => {
         const {value, selection} = elementState;
+
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/processors/repeated-decimal-separator-preprocessor.ts:22]: Should we drop redundant new empty line ?

File: projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts [hunk 10]
```diff
@@ -22,21 +23,28 @@ export function createThousandSeparatorPostprocessor({
...
+        } = extractAffixes(value, {
+            prefix,
+            postfix,
+        });
+
+        const [extractedMinus = ''] = cleanValueWithPossibleMinus.match(minusReg) || [];
+
+        const cleanValue = cleanValueWithPossibleMinus.replace(minusReg, '');
+
+        const [integerPart, decimalPart = ''] = cleanValue.split(decimalSeparator);
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts:43]:
```ts
    const {cleanValue, extractedPostfix, extractedPrefix} = extractAffixes(value, {
        prefix,
        postfix,
    });
    
    // drop this line
    // const [extractedMinus = ''] = cleanValue.match(minusReg) || [];

    const [integerPart, decimalPart = ''] = cleanValue
        .replace(CHAR_MINUS, '')
        .split(decimalSeparator);

    // [...]
    return {
            value:
                extractedPrefix +
                (cleanValue.includes(CHAR_MINUS) ? CHAR_MINUS : '') +
                processedIntegerPart +
                (cleanValue.includes(decimalSeparator) ? decimalSeparator : '') +
                decimalPart +
                extractedPostfix,
```

(the only possible minus inside `cleanValue` is negative sign => we can use just `includes`)

Comment (nsbarsukov) [reply projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts:43]: \+ remove `minusReg` constant

File: projects/kit/src/lib/masks/number/processors/pseudo-character-preprocessor.ts [hunk 11]
```diff
@@ -1,23 +1,42 @@
...
 
     return ({elementState, data}) => {
         const {value, selection} = elementState;
 
+        const {cleanValue, extractedPostfix, extractedPrefix} = extractAffixes(value, {
+            prefix,
+            postfix,
+        });
+
+        const newValue =
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/processors/pseudo-character-preprocessor.ts:31]:
```ts
const {value, selection} = elementState;
const {cleanValue, extractedPostfix, extractedPrefix} = extractAffixes(value, {
    prefix,
    postfix,
});

return {
    elementState: {
        selection,
        value:
            extractedPrefix +
            cleanValue.replace(pseudoCharactersRegExp, validCharacter) +
            extractedPostfix,
    },
    data: data.replace(pseudoCharactersRegExp, validCharacter),
};
```

File: projects/demo-integrations/src/tests/component-testing/number-postfix/number-postfix-with-point.cy.ts
Comment (nsbarsukov) [inline projects/demo-integrations/src/tests/component-testing/number-postfix/number-postfix-with-point.cy.ts:1]: Two tests fails with the following error
```
2 failing
  1) Number | postfix with point
       ` lbs.` postfix
         Complex: maskitoCaretGuard + maskitoAddOnFocusPlugin + maskitoRemoveOnBlurPlugin
           Empty textfield => Focus => | lbs.:
      Timed out retrying after [100](https://github.com/taiga-family/maskito/actions/runs/7514532360/job/20484955126?pr=816#step:5:101)00ms
      + expected - actual
      +' lbs.'
     

  2) Number | postfix with point
       ` lbs.` postfix
         Complex: maskitoCaretGuard + maskitoAddOnFocusPlugin + maskitoRemoveOnBlurPlugin
           Textfield contains only postfix => Blur => | Empty textfield:
      Timed out retrying after 10000ms
      + expected - actual
      +' lbs.'
     
```

Comment (nsbarsukov) [reply projects/demo-integrations/src/tests/component-testing/number-postfix/number-postfix-with-point.cy.ts:1]: I've investigated this problem. It is not problem of your PR.
It is just some race conditions because built-in angular-`mount` does not wait for the full initialization of all nested children.

Rebase your branch to get this fix:
* https://github.com/taiga-family/maskito/pull/908

**Comment by nsbarsukov** [comment]
@aktanoff Could you fix review comments, please ?

New major release is coming.
It can be cool to include this fix to new release.

**Review by nsbarsukov — APPROVED** [review]

File: projects/kit/src/lib/masks/number/utils/parse-number.ts (hunk 3 above)
Comment (nsbarsukov) [reply projects/kit/src/lib/masks/number/utils/parse-number.ts]: I will create the separate PR to implement zero-width workaround

Comment (namdien177) [reply projects/kit/src/lib/masks/number/utils/parse-number.ts]: I think you need to document this behavior and highlight it at the start.

I'm using `(input)` event and transforming the raw value from the input element into another format and I was caught off guard by this `CHAR_ZERO_WIDTH_SPACE` (in my case, `decimalSeparator: ''` will equal the prefix, thus, adding this character in the `event.target.value`).
