### PR TITLE
fix(kit): `Number` with `decimalZeroPadding=true` should erase everything on `.00`

### LINKED ISSUE #1085: 🐞 - `Number` with `decimalZeroPadding=true` should erase everything on `.00`
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://maskito.dev/kit/number/API?decimalZeroPadding=true&precision=2

### Case 1

1. Open https://maskito.dev/kit/number/API?decimalZeroPadding=true&precision=2
2. Type `0.12`
3. Select all (e.g. `Ctrl` + `A`)
4. Press `Backspace`

**Actual**: Empty textfield ✅
**Expected**: Empty textfield 

### Case 2

1. Open https://maskito.dev/kit/number/API?decimalZeroPadding=true&precision=2
2. Type `0.12`
3. `0.12|` => Backspace * 3 => `0|.00` => Backspace => ???

**Actual**: `.00` ❌
**Expected**: Empty textfield 

### Maskito version

2.0.2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
Closes #1085

### CODE REVIEW

File: projects/kit/src/lib/masks/number/number-mask.ts [hunk 1]
```diff
@@ -152,6 +153,7 @@ export function maskitoNumberOptionsGenerator({
                 prefix,
                 postfix,
             }),
+            emptyPostprocessor({prefix, postfix, decimalSeparator}),
```
Comment (nsbarsukov) [inline projects/kit/src/lib/masks/number/number-mask.ts:156]: `nullifyPostprocessor` / `emptifyPostprocessor` ? 🤔

**Review by KrollikRoddzer — APPROVED** [review]

File: projects/kit/src/lib/masks/number/utils/tests/to-number-parts.spec.ts [hunk 2]
```diff
@@ -0,0 +1,67 @@
+import {toNumberParts} from '../to-number-parts';
+
+describe('toNumberParts', () => {
```
Comment (splincode) [inline projects/kit/src/lib/masks/number/utils/tests/to-number-parts.spec.ts:3]: Please, add tests for other decimal separators

image

**Review by splincode — APPROVED** [review]

File: projects/kit/src/lib/masks/number/utils/tests/to-number-parts.spec.ts (hunk 2 above)
Comment (nsbarsukov) [reply projects/kit/src/lib/masks/number/utils/tests/to-number-parts.spec.ts:10]: ✅
